### PR TITLE
Card devexp_416 - Clean and update nodejs image to follow recent changes in STI

### PR DESCRIPTION
**Pull request by soltysh**
This as long as other image updates (https://github.com/openshift/ruby-20-centos/pull/7, 
https://github.com/openshift/wildfly-8-centos/pull/28) should be merged only after https://github.com/openshift/source-to-image/pull/98 is merged and origin is updated with latest STI version.

### CODE REVIEW

**Comment by soltysh** [comment]
Addressed @mfojtik's [comment](https://github.com/openshift/ruby-20-centos/pull/7#discussion_r22587383).

**Comment by bparees** [comment]
same comment here as in the ruby-20-centos PR regarding testing.

**Comment by soltysh** [comment]
See https://github.com/openshift/ruby-20-centos/pull/7#issuecomment-69719884

**Comment by bparees** [comment]
[test]

**Comment by danmcp** [comment]
[test]

**Comment by mfojtik** [comment]
[test] @danmcp sorry I forgot to enable this for nodejs, I will document how to do it properly in Jenkins, any suggestion where to to put that docs? :-)

**Pull request merged**
